settings:
  indexedsearch.view.templateRootPath:
    default: 'EXT:indexed_search/Resources/Private/Templates/'
    type: string
  indexedsearch.view.partialRootPath:
    default: 'EXT:indexed_search/Resources/Private/Partials/'
    type: string
  indexedsearch.view.layoutRootPath:
    default: 'EXT:indexed_search/Resources/Private/Layouts/'
    type: string
  indexedsearch.targetPid:
    default: 0
    type: int
  indexedsearch.rootPidList:
    default: ''
    type: string
